name: .NET

on:
  push:
    branches:
    - master
    paths:
    - 'src/**'
    - 'test/**'
    - 'build/**'
    - 'WeekendBot.sln'
  pull_request:
    branches: [ master ]
    paths:
    - 'src/**'
    - 'test/**'
    - 'build/**'
    - 'WeekendBot.sln'
env:
  build_directory: ./

jobs:
  xUnit_Windows_run:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore $env:build_directory --verbosity normal --configfile $env:build_directory/NuGet.config
    - name: Creating dummy config
      run: New-Item $env:build_directory/config.json
    - name: Build
      run: dotnet build $env:build_directory --no-restore
    - name: Test
      run: dotnet test $env:build_directory --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage"
    - name: Generate unit test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: xUnit Tests
        path: "test/**/*.trx"
        reporter: dotnet-trx
        fail-on-error: 'true'
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
